C /etc/drivers/nvidia-lts-tesla.toml
C /etc/drivers/nvidia-lts-open-gpu.toml
C /etc/drivers/nvidia-lts-open-gpu-copy-only.toml
C /etc/drivers/nvidia-lts-grid.toml
C /etc/drivers/nvidia-lts-grid-copy-only.toml
