C /etc/drivers/nvidia-pb-tesla.toml
C /etc/drivers/nvidia-pb-open-gpu.toml
C /etc/drivers/nvidia-pb-open-gpu-copy-only.toml
C /etc/drivers/nvidia-pb-grid.toml
C /etc/drivers/nvidia-pb-grid-copy-only.toml
